- name: Check tomcat is running or not
  hosts: all
  tasks: 
    - name: Check Tomcat is up or not
      ansible.builtin.shell: ps -ef | grep java | grep -v grep
      register: OUT
      ignore_errors: yes

    - name: Starting tomcat
      ansible.builtin.debug:
        msg: Tomcat is starting