- name: Demo on using variables
  hosts: all
  vars:
    URL: play.google.com
  vars_files:
    - demo-vars-file.yaml
    
  tasks:
    - name: Printing the url
      ansible.builtin.debug:
            msg: Value of URL is {{URL}}

    - name: Printing the URL with space
      ansible.builtin.debug: 
            msg: Value of URL is {{ URL }}

    - name: Printing the URL with quotes
      ansible.builtin.debug: 
            msg: "{{ URL }}"

    - name: Printing the CLI URL
      ansible.builtin.debug: 
            msg: "{{ CLI_URL }}"
      vars:
          CLI_URL: task-cli.google.com
            